name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - captum
  - cudatoolkit=11.3
  - datashader
  - deepchem
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - kaggle
  - matplotlib
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.9
  - python-language-server
  - pytorch=1.10
  - pytorch-lightning
  - pyviz_comms
  - rdkit
  - scikit-learn
  - scipy
  - tensorboard
  - torchaudio
  - torchinfo
  - torchmetrics
  - torchtext
  - torchvision
  - wandb
